apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: jmeter-nginx
    image: jmeter-nginx:v1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: jmeter-nginx
spec:
  selector:
    app: myapp
  ports:
  - port: 8080
    targetPort: 80
